version: "3"
services:
  node-app:
    build: .

    environment:
      - PORT=3000

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shivam
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
